# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"gcn_msg": "00_model.ipynb",
         "gcn_reduce": "00_model.ipynb",
         "GCN": "00_model.ipynb",
         "InnerProductDecoder": "00_model.ipynb",
         "GAEN": "00_model.ipynb",
         "GAE": "00_model.ipynb",
         "load_data": "01_utils.ipynb",
         "parse_index_file": "01_utils.ipynb",
         "load_graph": "01_utils.ipynb",
         "ismember": "01_utils.ipynb",
         "make_test_val_edges": "01_utils.ipynb",
         "get_acc": "01_utils.ipynb",
         "get_scores": "01_utils.ipynb"}

modules = ["model.py",
           "utils.py"]

doc_url = "https://leiyu-thunder.github.io/exp/"

git_url = "https://github.com/leiyu-thunder/exp/tree/master/"

def custom_doc_links(name): return None
